# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# add missing import
from selenium.webdriver.chrome.options import Options as ChromeOptions
from selenium.webdriver.chrome.service import Service

# add import firefox
from selenium.webdriver.firefox.options import Options as FirefoxOptions

class TestConnexion():
  def setup_method(self, method):
    is_firefox = bool(os.getenv('IS_FIREFOX'))
    # service = Service(executable_path='/full/path/to/chromedriver')
    # options = ChromeOptions()
    # options.binary_location = '/full/path/to/chrome'
    # self.driver = webdriver.Chrome(options=options, service=service)
#    self.driver = webdriver.Firefox()
    options = None
    if is_firefox:
      options = FirefoxOptions()
    else:
      options = ChromeOptions()
    self.driver = webdriver.Remote(command_executor='http://localhost:4444', options = options)

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_connexion(self):
    self.driver.get("http://5a4ef7c4-984e-4687-a293-442a633b3c57.pub.instances.scw.cloud/welcome")
    self.driver.find_element(By.ID, "identifier").click()
    self.driver.find_element(By.ID, "identifier").send_keys("gr")
    self.driver.find_element(By.ID, "register").click()
    self.driver.save_screenshot('login-ok.png')
    result = self.driver.find_element(By.ID, "identifier").text
    expected = 'GR'
    assert result.lower() == expected.lower()
    time.sleep(10)
  
