# Generated by Selenium IDE
import time
import os
from selenium import webdriver
from selenium.webdriver.common.by import By

# add missing import
from selenium.webdriver.chrome.options import Options as ChromeOptions

# add import firefox
from selenium.webdriver.firefox.options import Options as FirefoxOptions

class TestConnexion():
  def setup_method(self, method):
    is_firefox = bool(os.getenv('IS_FIREFOX'))
    options = None
    if is_firefox:
      options = FirefoxOptions()
    else:
      options = ChromeOptions()
    self.driver = webdriver.Remote(command_executor='http://localhost:4444', options = options)

    self.driver.implicitly_wait(30)

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_connexion(self):
    self.driver.get("http://5a4ef7c4-984e-4687-a293-442a633b3c57.pub.instances.scw.cloud/welcome")
    self.driver.find_element(By.ID, "identifier").click()
    self.driver.find_element(By.ID, "identifier").send_keys("gr")
    self.driver.find_element(By.ID, "register").click()
    self.driver.save_screenshot('login-ok.png')
    result = self.driver.find_element(By.ID, "identifier").text
    expected = 'GR'
    assert result.lower() == expected.lower()
    time.sleep(10)
  
