# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestnewsletter():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testnewsletter(self):
    self.driver.get("http://127.0.0.1:5000/welcome")
    self.driver.set_window_size(992, 644)
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.ID, "identifier").click()
    self.driver.find_element(By.ID, "identifier").send_keys("AA")
    self.driver.find_element(By.ID, "register").click()
  
